### ISSUE TITLE
SD upload

### ISSUE THREAD

**Issue by just-jason** [toxuin/ESPRINTER#7]
Hi, 
Did you ever make any progress on uploading speed of  files to the SD card ? or are we still on 3G Canada rates?
Jason

**Comment by toxuin** [comment]
Hi! This project probably should be archived or something at this point as I have not made any progress on it since. Good news is that dc42 seems to have drawn inspiration from it to create the duet wifi (which is nice). So yes, at this point we’re at Canada 3G rates :)

**Comment by just-jason** [comment]
It is a shame, it looks great, I would love to see the possibility to upgrade existing hardware with this project.
